### ISSUE TITLE
Vulkan-Hpp builds, does not compile in v1.1.109

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Headers#59]
See PR #58. Compiling a trivial test with clang++ gives this error:

``` 
In file included from hpptest.cpp:1:
./vulkan/vulkan.hpp:36506:5: error: constructor cannot be redeclared
    PerformanceValueDataINTEL( Bool32 valueBool_ )
    ^
./vulkan/vulkan.hpp:36491:5: note: previous declaration is here
    PerformanceValueDataINTEL( uint32_t value32_ = 0 )
    ^
./vulkan/vulkan.hpp:54489:31: error: use of undeclared identifier 'result'
    return createResultValue( result, VULKAN_HPP_NAMESPACE_STRING"::Devi...
                              ^
2 errors generated.
```

The problem is likely related to the fact that this is a union, not a struct, but beyond that I haven't looked into it.

**Comment by oddhack** [comment]
@mtavenrath @asuessenbach making sure this is on your radar - it is a blocker for Vulkan-Headers updates.

**Comment by mtavenrath** [comment]
@oddhack The problem is that uint32_t and Bool32 are actually the same type due to ```using Bool32 = uint32_t;```

For unions we have a constructor which accepts each possible value and so we have rethink how to handle those cases. One possible solution would be adding a special Bool32 struct which removes the ambiguity. Another solution would check for the type aliasing and generate the constructor for just a a single of those types. It'll take a few days to get this conflict resolved. 

```
  union PerformanceValueDataINTEL
  {
    PerformanceValueDataINTEL( uint32_t value32_ = 0 )
    {
      value32 = value32_;
    }

    PerformanceValueDataINTEL( Bool32 valueBool_ )
    {
      valueBool = valueBool_;
    }
```

My proposal for now to unblock the PR would be removing the Bool32 constrcutor in the vulkan.hpp header until we have a solution.

**Comment by mtavenrath** [comment]
@oddhack I've pushed a change to Vulkan-Hpp which removes the aliasing case from above.

**Comment by oddhack** [comment]
@mtavenrath was the Vulkan-Hpp change intended to fix the problem completely? I'm still getting compilation problems in the v1.1.110 Vulkan-Docs update (just the 'use of undeclared identifier 'result'' one, though).

**Comment by oddhack** [comment]
The second error turns out to be because the vkUninitializePerformanceApiINTEL XML has a 'void' return type but also sets successcodes and errorcodes attributes. I'm asking Intel how we should fix this; in the meantime a workaround from Vulkan-Hpp would let us move forward with headers.

**Comment by oddhack** [comment]
I think this has been fixed in both vk.xml and in the Hpp generator, so closing this (but there's another build issue, alas).
